name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Mise à jour chaque nuit
  workflow_dispatch: # Permet de lancer manuellement
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Première carte : En-tête et Infos Générales
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories
          config_timezone: Europe/Paris
          config_padding: 0, 8%

      # Deuxième carte : Langages + Habitudes
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stats.svg
          template: classic
          base: ""

          # Section Langages (sans indepth : utilise l'API GitHub standard)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6

          # Paramètres de rendu
          config_padding: 0, 10%
          config_output: svg
